/**
 * Generate `desktop/renderer/types/sidecar/*.ts` from the FastAPI OpenAPI.
 *
 * Source of truth: `src/market_analyser/data/types.py`. The Pydantic models
 * are dumped via the live FastAPI app factory, walked, and translated to TS
 * interfaces. This script is the boundary that keeps the renderer's TS in
 * sync with the sidecar.
 *
 * Workflow (chosen in Plan 0004 phase 6 — commit-time over build-time):
 *
 *   pnpm gen-types           # regenerate, overwrite on-disk files
 *   pnpm gen-types:check     # regenerate to memory, exit non-zero on drift
 *
 * Pre-commit runs `gen-types` so the staged diff carries the latest types;
 * CI runs `gen-types:check` so a missed regen breaks the pipeline.
 *
 * Plan 0004 phase 6 deviation note: this file is `.mjs`, not `.ts` as the
 * plan listed under "Files touched". The existing `desktop/scripts/` files
 * (`build-main.mjs`, `build-preload.mjs`, `playwright-global-setup.mjs`) are
 * all `.mjs`; matching the convention avoids adding a ts-node invocation
 * just for this one script.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DESKTOP_DIR = resolve(__dirname, '..')
const REPO_ROOT = resolve(DESKTOP_DIR, '..')
const OUTPUT_DIR = resolve(DESKTOP_DIR, 'renderer', 'types', 'sidecar')

// Allowlist — schemas to emit. Pydantic models declared anywhere in
// `src/market_analyser/` that the renderer actually needs. Add new entries
// here as the FastAPI surface grows (Quote, SymbolInfo, ...).
//
// Plan 0008 phase 5 adds the backtest result family. `BacktestResult`
// references `BacktestMetrics`, `EquityPoint`, and `Trade` via `$ref`; the
// generator emits cross-file `import type` lines for refs that land inside
// EMIT (see `mapType`). Refs to non-EMIT schemas (enums like `AnnotationKind`)
// continue to inline as before.
const EMIT = new Set([
  'Bar',
  'Annotation',
  'McpSecretRecord',
  'Trade',
  'EquityPoint',
  'BacktestMetrics',
  'BacktestResult',
  'BacktestRunSummary',
])

const HEADER = [
  '// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.',
  '// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic',
  '// models the sidecar surfaces (data/types.py, annotations/types.py,',
  '// api/mcp_secret.py).',
  '',
].join('\n')

// Single-line so Windows shell quoting doesn't split on newlines. Builds a
// fully-feathered app — in-memory engine for the annotations + backtest
// routes, placeholder mcp_secret + path for the settings router, a tmpdir
// for `runs_dir` — so every response_model the renderer consumes ends up in
// `components.schemas`. Without `backtest_runs_repository` AND `runs_dir`
// the `/backtests/*` routes are not mounted and `BacktestResult` /
// `BacktestRunSummary` would be absent from the OpenAPI dump.
const PYTHON_DUMP_SCRIPT = [
  'import json, tempfile, pathlib',
  'from market_analyser.api.app import create_app',
  'from market_analyser.persistence.annotations_repository import AnnotationsRepository',
  'from market_analyser.persistence.repositories.backtest_runs import BacktestRunsRepository',
  'from market_analyser.persistence.engine import apply_migrations, make_engine, make_session_factory',
  'engine = make_engine(":memory:")',
  'apply_migrations(engine)',
  'session_factory = make_session_factory(engine)',
  'annotations_repo = AnnotationsRepository(session_factory)',
  'backtest_repo = BacktestRunsRepository(session_factory)',
  'runs_dir = pathlib.Path(tempfile.mkdtemp(prefix="gen-types-runs-"))',
  "app = create_app(secret='gen-types-placeholder', mcp_secret='gen-types-placeholder', mcp_secret_path=pathlib.Path(tempfile.gettempdir())/'gen-types-placeholder.json', annotations_repository=annotations_repo, backtest_runs_repository=backtest_repo, runs_dir=runs_dir)",
  'print(json.dumps(app.openapi()))',
].join('; ')

function dumpOpenApi() {
  // shell: false so the script string passes through unmangled (Windows cmd
  // treats `;` and `&` as statement separators when shell: true is on).
  const result = spawnSync('uv', ['run', '--no-sync', 'python', '-c', PYTHON_DUMP_SCRIPT], {
    cwd: REPO_ROOT,
    encoding: 'utf-8',
    shell: false,
  })
  if (result.status !== 0) {
    process.stderr.write(result.stderr ?? '')
    throw new Error(`uv run python (OpenAPI dump) exited ${result.status ?? '?'}`)
  }
  return JSON.parse(result.stdout)
}

function kebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

/**
 * @param {object} schema       OpenAPI schema fragment.
 * @param {object} schemas      components.schemas map.
 * @param {Set<string>} imports Accumulator for cross-file imports. When a
 *                              `$ref` points to a name in the EMIT set, the
 *                              ref-name is added here AND the function
 *                              returns the bare name (e.g. `Trade`) instead
 *                              of inlining. Refs to non-EMIT schemas (enums,
 *                              unexported helpers) inline as before so
 *                              `Annotation.kind` still renders as
 *                              `'bullish_marker' | 'bearish_marker'`.
 */
function mapType(schema, schemas = {}, imports = new Set()) {
  if (!schema || typeof schema !== 'object') return 'unknown'
  if ('$ref' in schema && typeof schema.$ref === 'string') {
    const refName = schema.$ref.replace(/^#\/components\/schemas\//, '')
    if (EMIT.has(refName)) {
      imports.add(refName)
      return refName
    }
    const resolved = schemas[refName]
    if (resolved) return mapType(resolved, schemas, imports)
    return 'unknown'
  }
  if ('anyOf' in schema && Array.isArray(schema.anyOf)) {
    return schema.anyOf.map((s) => mapType(s, schemas, imports)).join(' | ')
  }
  if ('enum' in schema && Array.isArray(schema.enum)) {
    // Single quotes to match the repo's prettier config (singleQuote: true);
    // emitting JSON.stringify here would drift on every commit through the
    // pre-commit prettier --write pass.
    return schema.enum.map((v) => (typeof v === 'string' ? `'${v.replace(/'/g, "\\'")}'` : String(v))).join(' | ')
  }
  if ('type' in schema) {
    switch (schema.type) {
      case 'string':
        return 'string'
      case 'integer':
      case 'number':
        return 'number'
      case 'boolean':
        return 'boolean'
      case 'null':
        return 'null'
      case 'array':
        return `${mapType(schema.items ?? {}, schemas, imports)}[]`
      case 'object':
        if (
          'additionalProperties' in schema &&
          schema.additionalProperties &&
          typeof schema.additionalProperties === 'object'
        ) {
          return `Record<string, ${mapType(schema.additionalProperties, schemas, imports)}>`
        }
        return 'Record<string, unknown>'
      default:
        return 'unknown'
    }
  }
  return 'unknown'
}

function jsdocFor(propName, propSchema) {
  if (propSchema?.format === 'date-time') {
    return '  /** ISO 8601 UTC timestamp. */\n'
  }
  return ''
}

function renderFile(name, schema, schemas) {
  const required = new Set(schema.required ?? [])
  const props = schema.properties ?? {}
  const imports = new Set()
  const propLines = []
  for (const [propName, propSchema] of Object.entries(props)) {
    const optional = required.has(propName) ? '' : '?'
    const doc = jsdocFor(propName, propSchema)
    if (doc) propLines.push(doc.replace(/\n$/, ''))
    propLines.push(`  ${propName}${optional}: ${mapType(propSchema, schemas, imports)}`)
  }
  imports.delete(name) // a model never imports itself
  const importLines = [...imports]
    .sort()
    .map((dep) => `import type { ${dep} } from './${kebab(dep)}'`)
  const sections = [HEADER]
  if (importLines.length > 0) {
    sections.push(importLines.join('\n'), '')
  }
  sections.push(`export interface ${name} {`, ...propLines, '}', '')
  return sections.join('\n')
}

function generate() {
  const openapi = dumpOpenApi()
  const schemas = openapi.components?.schemas ?? {}
  const out = new Map()
  for (const name of EMIT) {
    const schema = schemas[name]
    if (!schema) {
      throw new Error(`schema ${name} not found in OpenAPI components.schemas`)
    }
    out.set(kebab(name) + '.ts', renderFile(name, schema, schemas))
  }
  return out
}

function loadExisting() {
  if (!existsSync(OUTPUT_DIR)) return new Map()
  const out = new Map()
  for (const entry of readdirSync(OUTPUT_DIR, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.ts')) {
      out.set(entry.name, readFileSync(join(OUTPUT_DIR, entry.name), 'utf-8'))
    }
  }
  return out
}

function writeAll(files) {
  mkdirSync(OUTPUT_DIR, { recursive: true })
  for (const [fileName, contents] of files) {
    writeFileSync(join(OUTPUT_DIR, fileName), contents, 'utf-8')
  }
}

function diff(generated, existing) {
  const drift = []
  for (const [fileName, contents] of generated) {
    const onDisk = existing.get(fileName)
    if (onDisk === undefined) {
      drift.push(`${fileName}: missing on disk`)
    } else if (onDisk !== contents) {
      drift.push(`${fileName}: content differs from generated output`)
    }
  }
  for (const fileName of existing.keys()) {
    if (!generated.has(fileName)) {
      drift.push(`${fileName}: present on disk but not emitted (stale; remove or add to EMIT)`)
    }
  }
  return drift
}

function main() {
  const checkMode = process.argv.includes('--check')
  const generated = generate()
  const existing = loadExisting()

  if (checkMode) {
    const drift = diff(generated, existing)
    if (drift.length > 0) {
      process.stderr.write(
        'gen-types --check: drift detected. Run `pnpm gen-types` and commit the result.\n',
      )
      for (const line of drift) {
        process.stderr.write(`  - ${line}\n`)
      }
      process.exit(1)
    }
    process.stdout.write('gen-types --check: no drift.\n')
    return
  }

  writeAll(generated)
  for (const fileName of generated.keys()) {
    process.stdout.write(`gen-types: wrote ${join('renderer', 'types', 'sidecar', fileName)}\n`)
  }
}

main()
