/**
 * Generate `desktop/renderer/types/sidecar/*.ts` from the FastAPI OpenAPI.
 *
 * Source of truth: `src/market_analyser/data/types.py`. The Pydantic models
 * are dumped via the live FastAPI app factory, walked, and translated to TS
 * interfaces. This script is the boundary that keeps the renderer's TS in
 * sync with the sidecar.
 *
 * Workflow (chosen in Plan 0004 phase 6 — commit-time over build-time):
 *
 *   pnpm gen-types           # regenerate, overwrite on-disk files
 *   pnpm gen-types:check     # regenerate to memory, exit non-zero on drift
 *
 * Pre-commit runs `gen-types` so the staged diff carries the latest types;
 * CI runs `gen-types:check` so a missed regen breaks the pipeline.
 *
 * Plan 0004 phase 6 deviation note: this file is `.mjs`, not `.ts` as the
 * plan listed under "Files touched". The existing `desktop/scripts/` files
 * (`build-main.mjs`, `build-preload.mjs`, `playwright-global-setup.mjs`) are
 * all `.mjs`; matching the convention avoids adding a ts-node invocation
 * just for this one script.
 */
import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DESKTOP_DIR = resolve(__dirname, '..')
const REPO_ROOT = resolve(DESKTOP_DIR, '..')
const OUTPUT_DIR = resolve(DESKTOP_DIR, 'renderer', 'types', 'sidecar')

// Allowlist — schemas to emit. Pydantic models declared in
// `src/market_analyser/data/types.py` that the renderer actually needs.
// Add new entries here as the FastAPI surface grows (Quote, SymbolInfo, ...).
const EMIT = new Set(['Bar'])

const HEADER = [
  '// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.',
  '// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic',
  '// models in `src/market_analyser/data/types.py`.',
  '',
].join('\n')

// Single-line so Windows shell quoting doesn't split on newlines.
const PYTHON_DUMP_SCRIPT =
  'import json; from market_analyser.api.app import create_app; ' +
  "print(json.dumps(create_app(secret='gen-types-placeholder').openapi()))"

function dumpOpenApi() {
  // shell: false so the script string passes through unmangled (Windows cmd
  // treats `;` and `&` as statement separators when shell: true is on).
  const result = spawnSync('uv', ['run', '--no-sync', 'python', '-c', PYTHON_DUMP_SCRIPT], {
    cwd: REPO_ROOT,
    encoding: 'utf-8',
    shell: false,
  })
  if (result.status !== 0) {
    process.stderr.write(result.stderr ?? '')
    throw new Error(`uv run python (OpenAPI dump) exited ${result.status ?? '?'}`)
  }
  return JSON.parse(result.stdout)
}

function kebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

function mapType(schema) {
  if (!schema || typeof schema !== 'object') return 'unknown'
  if ('anyOf' in schema && Array.isArray(schema.anyOf)) {
    return schema.anyOf.map(mapType).join(' | ')
  }
  if ('type' in schema) {
    switch (schema.type) {
      case 'string':
        return 'string'
      case 'integer':
      case 'number':
        return 'number'
      case 'boolean':
        return 'boolean'
      case 'null':
        return 'null'
      case 'array':
        return `${mapType(schema.items ?? {})}[]`
      case 'object':
        return 'Record<string, unknown>'
      default:
        return 'unknown'
    }
  }
  return 'unknown'
}

function jsdocFor(propName, propSchema) {
  if (propSchema?.format === 'date-time') {
    return '  /** ISO 8601 UTC timestamp. */\n'
  }
  return ''
}

function renderFile(name, schema) {
  const required = new Set(schema.required ?? [])
  const props = schema.properties ?? {}
  const lines = [HEADER, `export interface ${name} {`]
  for (const [propName, propSchema] of Object.entries(props)) {
    const optional = required.has(propName) ? '' : '?'
    const doc = jsdocFor(propName, propSchema)
    if (doc) lines.push(doc.replace(/\n$/, ''))
    lines.push(`  ${propName}${optional}: ${mapType(propSchema)}`)
  }
  lines.push('}', '')
  return lines.join('\n')
}

function generate() {
  const openapi = dumpOpenApi()
  const schemas = openapi.components?.schemas ?? {}
  const out = new Map()
  for (const name of EMIT) {
    const schema = schemas[name]
    if (!schema) {
      throw new Error(`schema ${name} not found in OpenAPI components.schemas`)
    }
    out.set(kebab(name) + '.ts', renderFile(name, schema))
  }
  return out
}

function loadExisting() {
  if (!existsSync(OUTPUT_DIR)) return new Map()
  const out = new Map()
  for (const entry of readdirSync(OUTPUT_DIR, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.ts')) {
      out.set(entry.name, readFileSync(join(OUTPUT_DIR, entry.name), 'utf-8'))
    }
  }
  return out
}

function writeAll(files) {
  mkdirSync(OUTPUT_DIR, { recursive: true })
  for (const [fileName, contents] of files) {
    writeFileSync(join(OUTPUT_DIR, fileName), contents, 'utf-8')
  }
}

function diff(generated, existing) {
  const drift = []
  for (const [fileName, contents] of generated) {
    const onDisk = existing.get(fileName)
    if (onDisk === undefined) {
      drift.push(`${fileName}: missing on disk`)
    } else if (onDisk !== contents) {
      drift.push(`${fileName}: content differs from generated output`)
    }
  }
  for (const fileName of existing.keys()) {
    if (!generated.has(fileName)) {
      drift.push(`${fileName}: present on disk but not emitted (stale; remove or add to EMIT)`)
    }
  }
  return drift
}

function main() {
  const checkMode = process.argv.includes('--check')
  const generated = generate()
  const existing = loadExisting()

  if (checkMode) {
    const drift = diff(generated, existing)
    if (drift.length > 0) {
      process.stderr.write(
        'gen-types --check: drift detected. Run `pnpm gen-types` and commit the result.\n',
      )
      for (const line of drift) {
        process.stderr.write(`  - ${line}\n`)
      }
      process.exit(1)
    }
    process.stdout.write('gen-types --check: no drift.\n')
    return
  }

  writeAll(generated)
  for (const fileName of generated.keys()) {
    process.stdout.write(`gen-types: wrote ${join('renderer', 'types', 'sidecar', fileName)}\n`)
  }
}

main()
