// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface AlertOut {
  id: number
  watch_id: number
  /** ISO 8601 UTC timestamp. */
  fired_at: string
  payload: Record<string, unknown>
}
