// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface Annotation {
  id?: string
  symbol: string
  timeframe: string
  /** ISO 8601 UTC timestamp. */
  event_ts: string
  kind: 'bullish_marker' | 'bearish_marker'
  label?: string | null
  agent_id?: string
  /** ISO 8601 UTC timestamp. */
  created_at?: string
}
