// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface BacktestRunSummary {
  run_id: string
  strategy_id: string
  strategy_version: string
  symbol: string
  timeframe: string
  /** ISO 8601 UTC timestamp. */
  range_start: string
  /** ISO 8601 UTC timestamp. */
  range_end: string
  total_return: number
  sharpe: number
  max_drawdown: number
  win_rate: number
  trade_count: number
  /** ISO 8601 UTC timestamp. */
  finished_at: string
  artifact_path: string
  engine_version: string
}
