// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface BacktestMetrics {
  total_return: number
  sharpe: number
  max_drawdown: number
  max_drawdown_duration_bars: number
  win_rate: number
  trade_count: number
  buy_and_hold_return: number
}
