// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models in `src/market_analyser/data/types.py`.

export interface Bar {
  symbol: string
  timeframe: string
  /** ISO 8601 UTC timestamp. */
  event_ts: string
  open: number
  high: number
  low: number
  close: number
  volume: number
  source: string
}
