// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface BucketStat {
  symbol: string
  horizon_bars: number
  conviction_bucket: 'low' | 'medium' | 'high'
  n: number
  sufficient: boolean
  hit_rate: number | null
  mean_r: number | null
}
