// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

import type { ScoredCallOut } from './scored-call-out'
import type { TrackRecord } from './track-record'

export interface GetTrackRecordResponse {
  track_record: TrackRecord
  recent: ScoredCallOut[]
  partial_reason: 'too_large' | null
  message: string | null
  total_available: number
  offset: number
  returned: number
}
