// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface Holding {
  symbol: string
  venue: 'binance' | 'defi' | 'manual'
  quantity: number
  avg_cost?: number | null
  /** ISO 8601 UTC timestamp. */
  as_of: string
  usd_value?: number | null
  pricing_source?: string | null
  kind?: string
}
