// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

import type { NewsItem } from './news-item'
import type { SentimentSample } from './sentiment-sample'

export interface NewsResponse {
  items: NewsItem[]
  sentiment: SentimentSample | null
  /** ISO 8601 UTC timestamp. */
  queried_at: string
}
