// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

import type { Holding } from './holding'

export interface PortfolioSummary {
  holdings: Holding[]
  unrealized_pnl_usd: number | null
  exposure_by_asset: Record<string, number>
  exposure_by_venue: Record<string, number>
  legs_as_of: Record<string, string>
  /** ISO 8601 UTC timestamp. */
  queried_at: string
}
