// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface PositionAlertOut {
  id: number
  watch_id: number
  wallet: string
  chain: string
  pool_address: string
  nft_token_id: number | null
  /** ISO 8601 UTC timestamp. */
  fired_at: string
  /** ISO 8601 UTC timestamp. */
  out_since: string
  hours_out: number
  tick_lower: number
  tick_upper: number
  current_tick: number
}
