// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

import type { PositionAlertOut } from './position-alert-out'

export interface PositionAlertsPage {
  alerts: PositionAlertOut[]
  total: number
}
