// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface PositionWatchOut {
  id: number
  wallet: string
  chain: string
  pool_address: string
  nft_token_id: number | null
  dwell_hours: number
  interval_seconds: number
  enabled: boolean
  source: string
  /** ISO 8601 UTC timestamp. */
  created_at: string
  out_since: string | null
  alert_fired: boolean
}
