// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface ScanChartPatternsRequest {
  symbol: string
  timeframe: string
  /** ISO 8601 UTC timestamp. */
  range_start: string
  /** ISO 8601 UTC timestamp. */
  range_end: string
  patterns?: string[] | null
  states?: string[] | null
}
