// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface ScoredCallOut {
  symbol: string
  timeframe: string
  strategy_id: string
  direction: 'long' | 'short'
  /** ISO 8601 UTC timestamp. */
  as_of_bar_ts: string
  horizon_bars: number
  conviction: number
  forecast_prob: number | null
  outcome_class: string
  realized_return: number | null
  realized_r: number | null
  directional_correct: boolean | null
  scored_at: string | null
}
