// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

import type { BucketStat } from './bucket-stat'
import type { ReliabilityBucket } from './reliability-bucket'

export interface TrackRecord {
  n: number
  sufficient: boolean
  min_n: number
  hit_rate: number | null
  mean_r: number | null
  brier: number | null
  calibration_n: number
  mean_forecast_prob: number | null
  observed_hit_rate: number | null
  reliability: ReliabilityBucket[]
  baseline_kind: 'buy_and_hold_over_horizon'
  baseline_hit_rate: number | null
  hit_rate_vs_baseline: number | null
  by_bucket: BucketStat[]
}
