// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface Trade {
  entry_bar_index: number
  exit_bar_index: number | null
  entry_price: number
  exit_price: number | null
  kind: 'long' | 'short'
}
