// AUTO-GENERATED by desktop/scripts/gen-types.mjs from the sidecar OpenAPI.
// DO NOT EDIT BY HAND. Run `pnpm gen-types` after changing the Pydantic
// models the sidecar surfaces (data/types.py, annotations/types.py,
// api/mcp_secret.py).

export interface WatchOut {
  id: number
  symbol: string
  timeframe: string
  kind: string
  params: Record<string, unknown>
  interval_seconds: number
  enabled: boolean
  last_state: boolean | null
  /** ISO 8601 UTC timestamp. */
  created_at: string
}
