/**
 * Plan 0091 phase 6: the momentum-oscillator mirrors are pure, lookahead-free, and
 * pinned to the Python `analysis.indicators` reference within 1e-6.
 *
 * The expected values below were generated by running the Python indicators over
 * the identical OHLC fixture (`stochastic(bars,3,2)`, `stochastic_rsi(closes,3,3)`,
 * `cci(bars,3)`, `williams_r(bars,3)`, `roc(closes,2)`) — the anti-drift guard: the
 * TS port must match these within 1e-6. Truncation-invariance (value at bar k is
 * unchanged whether fed `bars[0..=k]` or the full series) defends the no-lookahead
 * rule per indicator.
 */
import {
  computeCci,
  computeRoc,
  computeStochastic,
  computeStochasticRsi,
  computeWilliamsR,
} from './oscillators'
import type { Bar } from '../types/sidecar/bar'

function bar(eventTs: string, high: number, low: number, close: number): Bar {
  return {
    symbol: 'TEST',
    timeframe: '1d',
    event_ts: eventTs,
    open: close,
    high,
    low,
    close,
    volume: 1000,
    source: 'test',
  }
}

// (high, low, close) — the same fixture the Python reference values were generated
// from. Varied ranges so every oscillator is well-defined mid-series.
const OHLC: Array<[number, number, number]> = [
  [11, 9, 10],
  [13, 10, 12],
  [14, 11, 11],
  [12, 9, 10],
  [16, 11, 15],
  [17, 14, 16],
  [15, 12, 13],
  [14, 10, 11],
  [18, 13, 17],
  [19, 15, 18],
]
const FIXTURE: Bar[] = OHLC.map(([h, l, c], i) =>
  bar(`2026-04-${String(i + 1).padStart(2, '0')}T00:00:00+00:00`, h, l, c),
)

function timeAt(i: number): number {
  return Math.floor(new Date(FIXTURE[i].event_ts).getTime() / 1000)
}

/** Assert a mirror series matches `[i, value]` pairs from the Python reference. */
function expectSeries(series: { time: unknown; value: number }[], expected: [number, number][]) {
  expect(series).toHaveLength(expected.length)
  expected.forEach(([i, value], idx) => {
    expect(series[idx].time).toBe(timeAt(i))
    expect(series[idx].value).toBeCloseTo(value, 6)
  })
}

describe('computeStochastic (pinned to analysis.indicators.stochastic)', () => {
  it('matches %K and %D within 1e-6 (kPeriod=3, dPeriod=2)', () => {
    const { k, d } = computeStochastic(FIXTURE, 3, 2)
    expectSeries(k, [
      [3, 20.0],
      [4, 85.7142857143],
      [5, 87.5],
      [6, 33.3333333333],
      [7, 14.2857142857],
      [8, 87.5],
      [9, 88.8888888889],
    ])
    expectSeries(d, [
      [3, 30.0],
      [4, 52.8571428571],
      [5, 86.6071428571],
      [6, 60.4166666667],
      [7, 23.8095238095],
      [8, 50.8928571429],
      [9, 88.1944444444],
    ])
  })

  it('returns empty for invalid periods', () => {
    expect(computeStochastic(FIXTURE, 0, 2)).toEqual({ k: [], d: [] })
    expect(computeStochastic(FIXTURE, 3, 0)).toEqual({ k: [], d: [] })
  })

  it('is lookahead-free: %K/%D at bar k unchanged whether fed bars[0..=k] or full', () => {
    const full = computeStochastic(FIXTURE, 3, 2)
    for (let end = 4; end <= FIXTURE.length; end++) {
      const trunc = computeStochastic(FIXTURE.slice(0, end), 3, 2)
      const lastK = trunc.k[trunc.k.length - 1]
      const match = full.k.find((p) => p.time === lastK.time)
      expect(match).toBeDefined()
      expect(lastK.value).toBeCloseTo(match!.value, 6)
    }
  })
})

describe('computeStochasticRsi (pinned to analysis.indicators.stochastic_rsi)', () => {
  it('matches within 1e-6 (rsiPeriod=3, stochPeriod=3)', () => {
    expectSeries(computeStochasticRsi(FIXTURE, 3, 3), [
      [5, 100.0],
      [6, 0.0],
      [7, 0.0],
      [8, 100.0],
      [9, 100.0],
    ])
  })

  it('is lookahead-free', () => {
    const full = computeStochasticRsi(FIXTURE, 3, 3)
    for (let end = 6; end <= FIXTURE.length; end++) {
      const trunc = computeStochasticRsi(FIXTURE.slice(0, end), 3, 3)
      const last = trunc[trunc.length - 1]
      const match = full.find((p) => p.time === last.time)
      expect(match).toBeDefined()
      expect(last.value).toBeCloseTo(match!.value, 6)
    }
  })
})

describe('computeCci (pinned to analysis.indicators.cci)', () => {
  it('matches within 1e-6 (period=3)', () => {
    expectSeries(computeCci(FIXTURE, 3), [
      [2, 63.6363636364],
      [3, -100.0],
      [4, 100.0],
      [5, 77.7777777778],
      [6, -75.0],
      [7, -89.4736842105],
      [8, 100.0],
      [9, 70.0],
    ])
  })

  it('is lookahead-free', () => {
    const full = computeCci(FIXTURE, 3)
    for (let end = 3; end <= FIXTURE.length; end++) {
      const trunc = computeCci(FIXTURE.slice(0, end), 3)
      const last = trunc[trunc.length - 1]
      expect(last.value).toBeCloseTo(full.find((p) => p.time === last.time)!.value, 6)
    }
  })
})

describe('computeWilliamsR (pinned to analysis.indicators.williams_r)', () => {
  it('matches within 1e-6 (period=3), ranged -100..0', () => {
    expectSeries(computeWilliamsR(FIXTURE, 3), [
      [2, -60.0],
      [3, -80.0],
      [4, -14.2857142857],
      [5, -12.5],
      [6, -66.6666666667],
      [7, -85.7142857143],
      [8, -12.5],
      [9, -11.1111111111],
    ])
  })

  it('is lookahead-free', () => {
    const full = computeWilliamsR(FIXTURE, 3)
    for (let end = 3; end <= FIXTURE.length; end++) {
      const trunc = computeWilliamsR(FIXTURE.slice(0, end), 3)
      const last = trunc[trunc.length - 1]
      expect(last.value).toBeCloseTo(full.find((p) => p.time === last.time)!.value, 6)
    }
  })
})

describe('computeRoc (pinned to analysis.indicators.roc)', () => {
  it('matches within 1e-6 (period=2)', () => {
    expectSeries(computeRoc(FIXTURE, 2), [
      [2, 10.0],
      [3, -16.6666666667],
      [4, 36.3636363636],
      [5, 60.0],
      [6, -13.3333333333],
      [7, -31.25],
      [8, 30.7692307692],
      [9, 63.6363636364],
    ])
  })

  it('returns empty for invalid period', () => {
    expect(computeRoc(FIXTURE, 0)).toEqual([])
  })

  it('is lookahead-free', () => {
    const full = computeRoc(FIXTURE, 2)
    for (let end = 3; end <= FIXTURE.length; end++) {
      const trunc = computeRoc(FIXTURE.slice(0, end), 2)
      const last = trunc[trunc.length - 1]
      expect(last.value).toBeCloseTo(full.find((p) => p.time === last.time)!.value, 6)
    }
  })
})
