/**
 * Plan 0029 phase 2: direct unit test for the overlay registry. Defends:
 *   - `computeOverlayData` for ema/sma with hand-computed line values,
 *   - `[]` for an unregistered kind or a missing period,
 *   - `overlayColorFor` + `isSupportedOverlay` read from the registry,
 *   - the seam is single-source: adding ONE registry entry makes a previously
 *     unsupported kind supported, colored, and computable in one step.
 */
import type { UTCTimestamp } from 'lightweight-charts'

import {
  OVERLAY_REGISTRY,
  computeOverlayData,
  computeSupertrend,
  isSupportedOverlay,
  overlayColorFor,
  supertrendBands,
  type SupertrendPoint,
} from './overlays'
import type { Bar } from '../types/sidecar/bar'

function bar(eventTs: string, close: number): Bar {
  return {
    symbol: 'AAPL',
    timeframe: '1d',
    event_ts: eventTs,
    open: close,
    high: close + 1,
    low: close - 1,
    close,
    volume: 1000,
    source: 'test',
  }
}

// Four bars, closes [1, 2, 3, 10] — chosen so EMA and SMA diverge on the last
// point, so a kind→math mix-up can't pass.
const BARS: Bar[] = [
  bar('2026-04-01T00:00:00+00:00', 1),
  bar('2026-04-02T00:00:00+00:00', 2),
  bar('2026-04-03T00:00:00+00:00', 3),
  bar('2026-04-04T00:00:00+00:00', 10),
]
const T2 = Date.UTC(2026, 3, 3) / 1000
const T3 = Date.UTC(2026, 3, 4) / 1000

describe('computeOverlayData', () => {
  it('computes SMA(3): trailing mean over [1,2,3]=2 then [2,3,10]=5', () => {
    expect(computeOverlayData(BARS, { kind: 'sma', period: 3 })).toEqual([
      { time: T2, value: 2 },
      { time: T3, value: 5 },
    ])
  })

  it('computes EMA(3): seed=SMA(2)=2, then (10-2)*0.5+2=6', () => {
    expect(computeOverlayData(BARS, { kind: 'ema', period: 3 })).toEqual([
      { time: T2, value: 2 },
      { time: T3, value: 6 },
    ])
  })

  it('returns [] for an unregistered kind (rsi)', () => {
    expect(computeOverlayData(BARS, { kind: 'rsi', period: 14 })).toEqual([])
  })

  it.each([{ period: null }, { period: undefined }])(
    'returns [] when period is $period',
    ({ period }) => {
      expect(computeOverlayData(BARS, { kind: 'ema', period })).toEqual([])
    },
  )
})

describe('overlayColorFor', () => {
  it.each([
    { kind: 'ema' as const, color: '#2563eb' },
    { kind: 'sma' as const, color: '#f97316' },
  ])('returns the registry color for $kind', ({ kind, color }) => {
    expect(overlayColorFor({ kind, period: 20 })).toBe(color)
  })

  it('falls back to neutral grey for an unregistered kind', () => {
    expect(overlayColorFor({ kind: 'rsi', period: 14 })).toBe('#888888')
  })
})

describe('isSupportedOverlay', () => {
  it.each([
    { kind: 'ema' as const, supported: true },
    { kind: 'sma' as const, supported: true },
    { kind: 'supertrend' as const, supported: true },
    { kind: 'rsi' as const, supported: false },
    { kind: 'macd' as const, supported: false },
    { kind: 'bbands' as const, supported: false },
  ])('$kind → $supported', ({ kind, supported }) => {
    expect(isSupportedOverlay(kind)).toBe(supported)
  })
})

// ----------------------------------------------------------------------------
// Plan 0049 phase 9: client-side Supertrend, pinned against the Python reference.
// ----------------------------------------------------------------------------

function ohlcBar(eventTs: string, open: number, high: number, low: number, close: number): Bar {
  return {
    symbol: 'T',
    timeframe: '1d',
    event_ts: eventTs,
    open,
    high,
    low,
    close,
    volume: 1000,
    source: 'test',
  }
}

// 12 bars (a decline then a rally) forcing a downtrend→uptrend flip. `open` is
// irrelevant to Supertrend (it reads high/low/close), so it is set to `close`.
const ST_CLOSES = [100, 98, 96, 95, 97, 94, 92, 95, 99, 103, 106, 108]
const ST_HIGHS = [101, 99, 97, 96, 99, 96, 93, 97, 101, 105, 108, 110]
const ST_LOWS = [99, 97, 95, 93, 94, 92, 90, 92, 96, 100, 104, 106]
const ST_BARS: Bar[] = ST_CLOSES.map((c, i) =>
  ohlcBar(new Date(Date.UTC(2026, 4, 1 + i)).toISOString(), c, ST_HIGHS[i], ST_LOWS[i], c),
)

// Generated by `analysis.indicators.supertrend(ST_BARS, period=3, multiplier=2.0)`.
// Anti-drift guard: the TS port must match these within 1e-6.
const ST_EXPECTED: Array<{ i: number; value: number; direction: 1 | -1 }> = [
  { i: 3, value: 100.5, direction: -1 },
  { i: 4, value: 100.5, direction: -1 },
  { i: 5, value: 100.5, direction: -1 },
  { i: 6, value: 99.6481481481, direction: -1 },
  { i: 7, value: 99.6481481481, direction: -1 },
  { i: 8, value: 99.6481481481, direction: -1 },
  { i: 9, value: 91.9375857339, direction: 1 },
  { i: 10, value: 95.6250571559, direction: 1 },
  { i: 11, value: 98.4167047706, direction: 1 },
]

describe('computeSupertrend (pinned to the Python indicator)', () => {
  it('matches analysis.indicators.supertrend within 1e-6 and flips direction', () => {
    const points = computeSupertrend(ST_BARS, 3, 2.0)
    expect(points).toHaveLength(ST_EXPECTED.length)
    points.forEach((p, idx) => {
      const expected = ST_EXPECTED[idx]
      expect(p.time).toBe(Math.floor(Date.UTC(2026, 4, 1 + expected.i) / 1000))
      expect(p.value).toBeCloseTo(expected.value, 6)
      expect(p.direction).toBe(expected.direction)
    })
  })

  it('returns [] for too-few bars or invalid params', () => {
    expect(computeSupertrend(ST_BARS.slice(0, 3), 3, 2)).toEqual([])
    expect(computeSupertrend(ST_BARS, 0, 2)).toEqual([])
    expect(computeSupertrend(ST_BARS, 3, 0)).toEqual([])
  })

  it('is reachable through the generic registry as a single active-band line', () => {
    const line = computeOverlayData(ST_BARS, { kind: 'supertrend', period: 3, multiplier: 2 })
    expect(line).toHaveLength(ST_EXPECTED.length)
    expect(line[0]).toEqual({ time: Math.floor(Date.UTC(2026, 4, 4) / 1000), value: 100.5 })
  })
})

describe('supertrendBands (masked up/down series for flip colouring)', () => {
  it('puts the value on the active-direction series and a gap on the other', () => {
    const points: SupertrendPoint[] = [
      { time: 100 as UTCTimestamp, value: 10, direction: -1 },
      { time: 200 as UTCTimestamp, value: 20, direction: 1 },
    ]
    const { up, down } = supertrendBands(points)
    expect(up).toEqual([{ time: 100 }, { time: 200, value: 20 }])
    expect(down).toEqual([{ time: 100, value: 10 }, { time: 200 }])
  })
})

describe('the registry is the single seam for a new kind', () => {
  afterEach(() => {
    delete OVERLAY_REGISTRY.rsi
  })

  it('one entry makes a kind supported, colored, and computable at once', () => {
    expect(isSupportedOverlay('rsi')).toBe(false)

    OVERLAY_REGISTRY.rsi = {
      color: '#abcdef',
      compute: () => [{ time: T2 as UTCTimestamp, value: 42 }],
    }

    expect(isSupportedOverlay('rsi')).toBe(true)
    expect(overlayColorFor({ kind: 'rsi', period: 14 })).toBe('#abcdef')
    expect(computeOverlayData(BARS, { kind: 'rsi', period: 14 })).toEqual([{ time: T2, value: 42 }])
  })
})
