/**
 * Single-run backtest result view (Plan 0008 phase 5).
 *
 * Three panels:
 *   1. **Metrics table** — seven rows from `BacktestResult.metrics` plus
 *      buy-and-hold comparator. Values formatted via `lib/format.ts`.
 *   2. **Equity curve chart** — lightweight-charts baseline series with the
 *      result's `initial_capital` as the horizontal baseline. Above-baseline
 *      regions paint green (gains); below-baseline regions red (losses).
 *   3. **Trade log table** — one row per `Trade`, with derived entry/exit
 *      timestamps (looked up against `equity_curve[bar_index].ts`),
 *      computed P&L $ (`(exit-entry) * (initial_capital / entry)`) and
 *      P&L % (`(exit-entry) / entry`). Dangling trades render em-dashes
 *      and an "Open" status badge.
 *
 * Header carries the strategy / symbol / timeframe / range; subtitle shows
 * the engine version so a result regenerated by a different engine build
 * is visibly distinct.
 *
 * Test hook `window.__test_backtest_state__` mirrors the rendered series
 * data so the Playwright e2e and the Jest spec can assert the equity-curve
 * series exists and has the right point count without touching canvas pixels.
 */
import { useEffect, useMemo, useRef } from 'react'
import { ColorType, createChart } from 'lightweight-charts'
import type { IChartApi, ISeriesApi, LineData, UTCTimestamp } from 'lightweight-charts'

import {
  formatDate,
  formatDateTime,
  formatInt,
  formatPct,
  formatRatio,
  formatUsd,
  formatUsdSigned,
} from '../lib/format'
import type { BacktestResult } from '../types/sidecar/backtest-result'
import type { EquityPoint } from '../types/sidecar/equity-point'
import type { Trade } from '../types/sidecar/trade'
import styles from './BacktestView.module.css'

declare global {
  interface Window {
    __test_backtest_state__?: {
      run_id: string
      strategy_id: string
      symbol: string
      timeframe: string
      equityCurve: ReadonlyArray<{ time: number; value: number }>
      initial_capital: number
    }
  }
}

interface BacktestViewProps {
  result: BacktestResult
  onBack?: () => void
}

export function BacktestView({ result, onBack }: BacktestViewProps): JSX.Element {
  const tradeRows = useMemo(
    () => decorateTrades(result.trades, result.equity_curve, result.initial_capital),
    [result.trades, result.equity_curve, result.initial_capital],
  )

  return (
    <section className={styles.root} aria-label={`Backtest ${result.run_id}`}>
      <header className={styles.header}>
        {onBack && (
          <button
            type="button"
            onClick={onBack}
            className={styles.backButton}
            data-testid="backtest-back"
          >
            ← Recent backtests
          </button>
        )}
        <h2 className={styles.title} data-testid="backtest-title">
          {result.strategy_id} v{result.strategy_version} · {result.symbol} · {result.timeframe} ·{' '}
          {formatDate(result.range_start)} → {formatDate(result.range_end)}
        </h2>
        <p className={styles.subtitle} data-testid="backtest-engine-version">
          engine v{result.engine_version}
        </p>
      </header>

      <section className={styles.metricsSection} aria-labelledby="metrics-heading">
        <h3 id="metrics-heading" className={styles.sectionTitle}>
          Metrics
        </h3>
        <dl className={styles.metrics} data-testid="backtest-metrics">
          <MetricRow
            label="Total return"
            value={formatPct(result.metrics.total_return)}
            testId="metric-total-return"
          />
          <MetricRow
            label="Sharpe"
            value={formatRatio(result.metrics.sharpe)}
            testId="metric-sharpe"
          />
          <MetricRow
            label="Max drawdown"
            value={formatPct(result.metrics.max_drawdown)}
            testId="metric-max-drawdown"
          />
          <MetricRow
            label="Max DD duration"
            value={`${formatInt(result.metrics.max_drawdown_duration_bars)} bars`}
            testId="metric-max-dd-duration"
          />
          <MetricRow
            label="Win rate"
            value={formatPct(result.metrics.win_rate)}
            testId="metric-win-rate"
          />
          <MetricRow
            label="Trade count"
            value={formatInt(result.metrics.trade_count)}
            testId="metric-trade-count"
          />
          <MetricRow
            label="Buy & hold"
            value={formatPct(result.metrics.buy_and_hold_return)}
            testId="metric-buy-and-hold"
          />
        </dl>
      </section>

      <section className={styles.chartSection} aria-labelledby="equity-heading">
        <h3 id="equity-heading" className={styles.sectionTitle}>
          Equity curve
        </h3>
        <EquityCurveChart
          points={result.equity_curve}
          initialCapital={result.initial_capital}
          runId={result.run_id}
          strategyId={result.strategy_id}
          symbol={result.symbol}
          timeframe={result.timeframe}
        />
      </section>

      <section className={styles.tradesSection} aria-labelledby="trades-heading">
        <h3 id="trades-heading" className={styles.sectionTitle}>
          Trade log ({tradeRows.length})
        </h3>
        {tradeRows.length === 0 ? (
          <p className={styles.emptyTrades} data-testid="trades-empty">
            No trades in this run.
          </p>
        ) : (
          <div className={styles.tableScroll}>
            <table className={styles.trades} data-testid="trades-table">
              <thead>
                <tr>
                  <th scope="col">Entry</th>
                  <th scope="col">Exit</th>
                  <th scope="col" className={styles.numCol}>
                    Entry $
                  </th>
                  <th scope="col" className={styles.numCol}>
                    Exit $
                  </th>
                  <th scope="col" className={styles.numCol}>
                    P&amp;L $
                  </th>
                  <th scope="col" className={styles.numCol}>
                    P&amp;L %
                  </th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                {tradeRows.map((row, idx) => (
                  <tr key={`${row.entryTs}-${idx}`}>
                    <td>{row.entryTs ? formatDateTime(row.entryTs) : '—'}</td>
                    <td>{row.exitTs ? formatDateTime(row.exitTs) : '—'}</td>
                    <td className={styles.numCol}>{formatUsd(row.trade.entry_price)}</td>
                    <td className={styles.numCol}>
                      {row.trade.exit_price === null ? '—' : formatUsd(row.trade.exit_price)}
                    </td>
                    <td className={styles.numCol}>
                      {row.pnlUsd === null ? '—' : formatUsdSigned(row.pnlUsd)}
                    </td>
                    <td className={styles.numCol}>
                      {row.pnlPct === null ? '—' : formatPct(row.pnlPct)}
                    </td>
                    <td>
                      {row.isOpen ? (
                        <span className={styles.openBadge} data-testid="trade-open-badge">
                          Open
                        </span>
                      ) : (
                        <span className={styles.closedBadge}>Closed</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </section>
  )
}

interface MetricRowProps {
  label: string
  value: string
  testId: string
}

function MetricRow({ label, value, testId }: MetricRowProps): JSX.Element {
  return (
    <div className={styles.metricRow} data-testid={testId}>
      <dt>{label}</dt>
      <dd>{value}</dd>
    </div>
  )
}

interface EquityCurveChartProps {
  points: EquityPoint[]
  initialCapital: number
  runId: string
  strategyId: string
  symbol: string
  timeframe: string
}

function EquityCurveChart({
  points,
  initialCapital,
  runId,
  strategyId,
  symbol,
  timeframe,
}: EquityCurveChartProps): JSX.Element {
  const containerRef = useRef<HTMLDivElement>(null)
  const chartRef = useRef<IChartApi | null>(null)
  const seriesRef = useRef<ISeriesApi<'Baseline'> | null>(null)

  // Compute series data once per `points` change. Stable across renders so
  // both the chart and the test-hook see the same array identity.
  const seriesData = useMemo<LineData[]>(
    () =>
      points.map((p) => ({
        time: Math.floor(new Date(p.ts).getTime() / 1000) as UTCTimestamp,
        value: p.equity,
      })),
    [points],
  )

  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const computed = getComputedStyle(container)
    const textColor = computed.getPropertyValue('--color-fg').trim() || '#1a1a1a'
    const borderColor = computed.getPropertyValue('--color-border').trim() || '#e5e5e5'

    const chart = createChart(container, {
      layout: {
        background: { type: ColorType.Solid, color: 'transparent' },
        textColor,
      },
      grid: {
        vertLines: { color: borderColor },
        horzLines: { color: borderColor },
      },
      timeScale: { timeVisible: false, secondsVisible: false },
      rightPriceScale: { borderColor },
      autoSize: true,
    })

    // Baseline series colors gains (above initial_capital) green and losses red.
    // The numerical values are sober — high-saturation reds and greens read as
    // alarms; we want a calm "ok / not ok" gradient.
    const series = chart.addBaselineSeries({
      baseValue: { type: 'price', price: initialCapital },
      topLineColor: 'rgba(22, 163, 74, 1)',
      topFillColor1: 'rgba(22, 163, 74, 0.28)',
      topFillColor2: 'rgba(22, 163, 74, 0.05)',
      bottomLineColor: 'rgba(220, 38, 38, 1)',
      bottomFillColor1: 'rgba(220, 38, 38, 0.05)',
      bottomFillColor2: 'rgba(220, 38, 38, 0.28)',
      lineWidth: 2,
    })

    chartRef.current = chart
    seriesRef.current = series

    return () => {
      chart.remove()
      chartRef.current = null
      seriesRef.current = null
    }
  }, [initialCapital])

  useEffect(() => {
    const chart = chartRef.current
    const series = seriesRef.current
    if (!chart || !series) return
    series.setData(seriesData)
    chart.timeScale().fitContent()
    window.__test_backtest_state__ = {
      run_id: runId,
      strategy_id: strategyId,
      symbol,
      timeframe,
      equityCurve: seriesData.map((d) => ({ time: d.time as number, value: d.value })),
      initial_capital: initialCapital,
    }
  }, [seriesData, runId, strategyId, symbol, timeframe, initialCapital])

  return (
    <div
      ref={containerRef}
      className={styles.equityChart}
      data-testid="equity-chart"
      role="img"
      aria-label={`Equity curve for ${symbol} ${timeframe}, ${points.length} points`}
    />
  )
}

interface DecoratedTrade {
  trade: Trade
  entryTs: string | null
  exitTs: string | null
  pnlUsd: number | null
  pnlPct: number | null
  isOpen: boolean
}

/**
 * Exported so the Jest spec can assert the P&L derivation without rendering.
 * `equity_curve[bar_index].ts` is the source for entry/exit timestamps —
 * `Trade` itself only carries `entry_bar_index` / `exit_bar_index`, and the
 * engine's `BacktestResult` does not carry the bars list separately. The
 * equity curve has one entry per bar (Plan 0008 phase 1 invariant), so the
 * indices are aligned.
 */
export function decorateTrades(
  trades: Trade[],
  equityCurve: EquityPoint[],
  initialCapital: number,
): DecoratedTrade[] {
  return trades.map((trade) => {
    const entryTs = lookupTs(equityCurve, trade.entry_bar_index)
    const exitTs =
      trade.exit_bar_index !== null ? lookupTs(equityCurve, trade.exit_bar_index) : null
    if (trade.exit_price === null) {
      return { trade, entryTs, exitTs, pnlUsd: null, pnlPct: null, isOpen: true }
    }
    // P&L formulas pinned by Plan 0008 phase 5 done-when:
    //   P&L $ = (exit - entry) * (initial_capital / entry)
    //   P&L % = (exit - entry) / entry
    const delta = trade.exit_price - trade.entry_price
    const pnlPct = delta / trade.entry_price
    const pnlUsd = delta * (initialCapital / trade.entry_price)
    return { trade, entryTs, exitTs, pnlUsd, pnlPct, isOpen: false }
  })
}

function lookupTs(equityCurve: EquityPoint[], barIndex: number): string | null {
  if (barIndex < 0 || barIndex >= equityCurve.length) return null
  return equityCurve[barIndex].ts
}
